# Game parameters
SIZE = 4
BLACK_TILES = 3
ENDURANCE_START_TIMER = 10
EUNDRANCE_TIME_GAIN = 10
ENDURANCE_TIME_GAIN_THRESHOLD = 40
PATTERN_START_TIMER = 0
PATTERN_SIZE = 4
PATTERN_AMOUNT = 15
FRENZY_START_TIMER = 30
FRENZY_SCORE_STEPS = 5

# Sceen 
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1440
BACKGROUND_COLOR = (38, 38, 38)

# Game window
GAME_WIDTH = 850
GAME_HEIGHT = 850
GAME_START_POS_X = (SCREEN_WIDTH - GAME_WIDTH) / 2
GAME_START_POS_Y = (SCREEN_HEIGHT - GAME_HEIGHT) / 2

# Tile settings
TILE_WIDTH = GAME_WIDTH / SIZE
TILE_HEIGHT = GAME_HEIGHT / SIZE
TILE_BORDER = 1
WHITE_TILE_COLOR = (255, 255, 255)
BLACK_TILE_COLOR = (0, 0, 0)
TILE_BORDER_COLOR = (97, 97, 97)

# Text settings
INFO_TEXT_SIZE = 50
INFO_TEXT_COLOR = (255, 255, 255)

NUMERICAL_TEXT_SIZE = 80
NUMERICAL_TEXT_COLOR = (0, 0, 255)

TEXT_MARGIN = 25

# 
REFRESH_RATE = 60

# Save file
SAVE_PATH = 'stats.txt'

# MODES
ENDURANCE = 0
PATTERN = 1
FRENZY = 2